[params]

# Pour SEO ld+json
# Correspondance entre :
#   - les varialbles de config.toml (qui changent selon les sites)
#   - et les variables pour le module SEO qui sont imposées
# Indiquer les variables de ce site qui correspondent aux besoins
# NE PAS mettre <site.Params.xxx>, mais uniqueent le <xxx> qui est en dessous

[params.seo_json]
  # basic used by website
  social_facebook   = "my real variable name"
  social_twitter    = "my real variable name"
  social_instagram  = "my real variable name"
  image             = "my real variable name"
  defaultKeywords   = "my real variable name"

  # Used by localbusiness
  logo              = "my real variable name"
  geo_type          = "my real variable name"
  geo_latitude      = "my real variable name"
  geo_longitude     = "my real variable name"

  officeAddress       = "my real variable name"
  officeAddressVille  = "my real variable name"
  officeAddressRegion = "my real variable name"
  officeAddressCP     = "my real variable name"
  officeAddressPays   = "my real variable name"

  # propriété phone doit être unique pour schema.org
  officePhone = "my real variable name"

  officeHorairesJours = "my real variable name"
  officeHorairesOpen  = "my real variable name"
  officeHorairesClose = "my real variable name"
